[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
addopts = "-ra --color=yes"
markers = [
    "fcompare: show failed comparison",
    "slow: run slow tests",
]
# for future coverage test
# addopts = "-ra --cov --cov-report=xml --cov-config=.coveragerc --color=yes"